/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_paulasmuth_libsmatrix_SparseMatrix */

#ifndef _Included_com_paulasmuth_libsmatrix_SparseMatrix
#define _Included_com_paulasmuth_libsmatrix_SparseMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_paulasmuth_libsmatrix_SparseMatrix
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_paulasmuth_libsmatrix_SparseMatrix_init
  (JNIEnv *, jobject);

/*
 * Class:     com_paulasmuth_libsmatrix_SparseMatrix
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_paulasmuth_libsmatrix_SparseMatrix_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
